name = "peel-edge-demo"
version = "0.1.0"
require_wasm_sha256 = true

cells = [
    "../../pulp-engines/routing-state-sqlite-cell/pulp.cell.toml",
    "../../pulp-engines/edge-admission-sqlite-cell/pulp.cell.toml",
    "../../pulp-engines/framed-edge-demo-host-cell/pulp.cell.toml",
    "../../pulp-engines/routed-udp-relay-host-cell/pulp.cell.toml",
    "../../pulp-engines/routed-tcp-relay-host-cell/pulp.cell.toml",
    "../api-cell/pulp.cell.toml",
    "../../pulp-engines/http-json-cell/pulp.cell.toml",
    "lua-orchestrator.cell.toml",
]

[orchestrator]
manifest = "lua-orchestrator.cell.toml"
script = "peel.lua"
sha256 = "0fe82e3d94221ae30d2e96dc3c20f8f10dbcdcb2f738f3380a97cfd463b32f29"
