schema_version = 1
name = "peel"
version = "0.2.0"

cells = [
    "../../pulp-engines/routing-state-sqlite-cell/pulp.cell.toml",
    "../../pulp-engines/edge-admission-sqlite-cell/pulp.cell.toml",
    "../../pulp-engines/routed-udp-relay-host-cell/pulp.cell.toml",
    "../../pulp-engines/routed-tcp-relay-host-cell/pulp.cell.toml",
    "../api-cell/pulp.cell.toml",
    "../../pulp-engines/http-json-cell/pulp.cell.toml",
    "lua-orchestrator.cell.toml",
]

[orchestrator]
manifest = "lua-orchestrator.cell.toml"
script = "peel.lua"
sha256 = "404de98ca88f76c161213469caad68319bc89ccaa2385bc046375b96a5ec0bf7"
