schema_version = 1
name = "peel"
version = "0.2.0"

cells = [
    "../../pulp-engines/routing-state-sqlite-cell/pulp.cell.toml",
    "../../pulp-engines/routed-udp-relay-host-cell/pulp.cell.toml",
    "../api-cell/pulp.cell.toml",
    "../../pulp-engines/http-json-cell/pulp.cell.toml",
    "lua-orchestrator.cell.toml",
]

[orchestrator]
manifest = "lua-orchestrator.cell.toml"
script = "peel.lua"
sha256 = "32f8e2cac1c070a66c6646db8d5d225176f241d4a9a717d45444551a9f0474bc"
