schema_version = 1
name = "peel"
version = "0.1.0"

cells = [
    "../owner-cell/pulp.cell.toml",
    "../pulp-cell/pulp.cell.toml",
    "../api-cell/pulp.cell.toml",
    "../http-client-cell/pulp.cell.toml",
    "lua-orchestrator.cell.toml",
]

[orchestrator]
manifest = "lua-orchestrator.cell.toml"
script = "peel.lua"
sha256 = "80eb76ab5712b879561d625c98d8e04787f7fa2c718d84a0345d6e15cb0f6093"
